# Generated by Django 5.0.6 on 2024-06-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='pass', max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio', models.DateField(null=True)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=30)),
                ('obv', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'lista_espera',
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('concepto', models.CharField(blank=True, max_length=16, null=True)),
                ('tipopago', models.CharField(blank=True, db_column='tipoPago', max_length=13, null=True)),
                ('fecha', models.DateField()),
                ('num_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
            ],
            options={
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio', models.DateField(null=True)),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'salas',
            },
        ),
        migrations.CreateModel(
            name='TiposTurnos',
            fields=[
                ('tipo', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_turnos',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('asistio', models.BooleanField(default=False)),
                ('dni_alumno', models.ForeignKey(blank=True, db_column='dni_alumno', null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.alumnos')),
            ],
            options={
                'db_table': 'asistencia_alumnos',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaProfesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('asistio', models.BooleanField(default=False)),
                ('dni_profesor', models.ForeignKey(blank=True, db_column='dni_profesor', null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.profesores')),
            ],
            options={
                'db_table': 'asistencia_profesores',
            },
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('monto', models.FloatField()),
                ('mes', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('estado', models.CharField(max_length=6)),
                ('dni_alumno', models.ForeignKey(blank=True, db_column='dni_alumno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.alumnos')),
            ],
            options={
                'db_table': 'cuotas',
                'unique_together': {('mes', 'ano', 'dni_alumno')},
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('hora', models.TimeField()),
                ('dni_alumno', models.ForeignKey(blank=True, db_column='dni_alumno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.alumnos')),
                ('dni_profesor', models.ForeignKey(blank=True, db_column='dni_profesor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.profesores')),
                ('num_sala', models.ForeignKey(blank=True, db_column='num_sala', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.salas')),
                ('tipo', models.ForeignKey(blank=True, db_column='tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.tiposturnos')),
            ],
            options={
                'db_table': 'turnos',
                'unique_together': {('hora', 'dni_alumno')},
            },
        ),
    ]
