# Generated by Django 5.0.6 on 2024-05-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nombrecompleto',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
