# Generated by Django 5.0.6 on 2024-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turnos',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='turnos',
            unique_together={('hora', 'dni_alumno', 'dia')},
        ),
    ]
