# Generated by Django 5.0.6 on 2024-06-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_turnos_unique_together_alter_turnos_dia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistenciaalumnos',
            unique_together={('dni_alumno', 'fecha')},
        ),
    ]
