# Generated by Django 5.0.6 on 2024-06-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_remove_persona_nombrecompleto_persona_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='pass', max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia_alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaProfesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia_profesores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('monto', models.FloatField()),
                ('mes', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('estado', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'cuotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('concepto', models.CharField(blank=True, max_length=16, null=True)),
                ('tipopago', models.CharField(blank=True, db_column='tipoPago', max_length=13, null=True)),
                ('fecha', models.DateField()),
                ('num_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'profesores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'salas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposTurnos',
            fields=[
                ('tipo', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_turnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('dia', models.DateField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'turnos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
