# Generated by Django 5.0.6 on 2024-06-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_admin_alumnos_asistenciaalumnos_asistenciaprofesores_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='alumnos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='asistenciaalumnos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='asistenciaprofesores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cuotas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movimientos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profesores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiposturnos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={},
        ),
    ]
